version: "3.6"

services:
  tracker:
    image: registry.gitlab.com/skinholdings/delivery-tracker:v1.2.0
    build:
      context: .
    expose:
      - 9229
    ports:
      - 9224:9229
    environment:
      API_URL: ""
      API_USER_EMAIL: ""
      API_USER_PASSWORD: ""

      TRACKING_STATUS_SELECTOR: ""
      TRACKING_URL: ""

      SLACK_WEBHOOK_URL: ""


