version: "3.6"

services:
  tracker:
    image: registry.gitlab.com/skinholdings/delivery-tracker:v1.0.0
    build:
      context: .
    expose:
      - 9229
    ports:
      - 9224:9229
    environment:
      API_URL: 'https://c9af815c.ngrok.io/api'
      API_USER_EMAIL: 'superadmin@drakemall.com'
      API_USER_PASSWORD: 'ohgeepearo6kaW4uVeu9Poovai6jaikooquait4Iush9aas0eek6hephieHaish5'

      TRACKING_STATUS_SELECTOR: '[data-name] .text-capitalize'
      TRACKING_URL: 'https://t.17track.net/en#nums={trackingCode}'

      SLACK_WEBHOOK_URL: 'sadf'


